In [153]:
# Installing dependencies
import boto3
import os
import pandas as pd
import json
import re

In [154]:
pd.options.display.max_columns=100

In [155]:
# Listing files
os.listdir('assets/')

['create-forecast.png',
 'sample-data.png',
 'covid_19_week_4',
 '.DS_Store',
 'covid_19_week_5',
 'dataset-import-job.png',
 'predicted-s3-files.png',
 'forecast-working.png',
 'dataset-creation.png',
 'automl_predictor.png',
 'forecast-lookup-US-2.png',
 'dataset-group-creation.png',
 'covid_19_week_1',
 '.ipynb_checkpoints',
 'forecast-lookup-US.png']

In [68]:
covid19_week_1_path = 'assets/covid_19_week_1/target_time_series/'
train_df = pd.read_csv(covid19_week_1_path + "train.csv")
train_df.head(3)

,Id,Province/State,Country/Region,Lat,Long,Date,ConfirmedCases,Fatalities
0,1,NaN,Afghanistan,33.0,65.0,2020-01-22,0.0,0.0
1,2,NaN,Afghanistan,33.0,65.0,2020-01-23,0.0,0.0
2,3,NaN,Afghanistan,33.0,65.0,2020-01-24,0.0,0.0

In [156]:
covid19_week_5_path = 'assets/covid_19_week_5/target_time_series/'
train_df = pd.read_csv(covid19_week_5_path + "train.csv")
train_df.head(3)

,Id,County,Province_State,Country_Region,Population,Weight,Date,Target,TargetValue
0,1,NaN,NaN,Afghanistan,27657145,0.058359,2020-01-23,ConfirmedCases,0.0
1,2,NaN,NaN,Afghanistan,27657145,0.583587,2020-01-23,Fatalities,0.0
2,3,NaN,NaN,Afghanistan,27657145,0.058359,2020-01-24,ConfirmedCases,0.0

In [157]:
train_df['Target'].unique()

array(['ConfirmedCases', 'Fatalities'], dtype=object)

In [167]:
train_df.loc[train_df['Target'] == 'ConfirmedCases'] \
.to_csv('assets/covid_19_week_5/target_time_series/confirmedcases_train.csv', index=False)

In [168]:
confirmedcases_df = pd.read_csv('assets/covid_19_week_5/target_time_series/confirmedcases_train.csv')

In [169]:
confirmedcases_df.head()

,Id,County,Province_State,Country_Region,Population,Weight,Date,Target,TargetValue
0,1,NaN,NaN,Afghanistan,27657145,0.058359,2020-01-23,ConfirmedCases,0.0
1,3,NaN,NaN,Afghanistan,27657145,0.058359,2020-01-24,ConfirmedCases,0.0
2,5,NaN,NaN,Afghanistan,27657145,0.058359,2020-01-25,ConfirmedCases,0.0
3,7,NaN,NaN,Afghanistan,27657145,0.058359,2020-01-26,ConfirmedCases,0.0
4,9,NaN,NaN,Afghanistan,27657145,0.058359,2020-01-27,ConfirmedCases,0.0

In [170]:
train_df.loc[train_df['Target'] == 'Fatalities'] \
.to_csv('assets/covid_19_week_5/target_time_series/fatalities_train.csv', index=False)

In [70]:
covid19_week_1_path = 'assets/covid_19_week_5/target_time_series/'
train_df = pd.read_csv(covid19_week_1_path + "train.csv")
train_df.head(3)

,Id,County,Province_State,Country_Region,Population,Weight,Date,Target,TargetValue
0,1,NaN,NaN,Afghanistan,27657145,0.058359,2020-01-23,ConfirmedCases,0.0
1,2,NaN,NaN,Afghanistan,27657145,0.583587,2020-01-23,Fatalities,0.0
2,3,NaN,NaN,Afghanistan,27657145,0.058359,2020-01-24,ConfirmedCases,0.0

,Id,Province/State,Country/Region,Lat,Long,Date,ConfirmedCases,Fatalities
0,1,NaN,Afghanistan,33.0,65.0,2020-01-22,0.0,0.0
1,2,NaN,Afghanistan,33.0,65.0,2020-01-23,0.0,0.0
2,3,NaN,Afghanistan,33.0,65.0,2020-01-24,0.0,0.0
3,4,NaN,Afghanistan,33.0,65.0,2020-01-25,0.0,0.0
4,5,NaN,Afghanistan,33.0,65.0,2020-01-26,0.0,0.0

In [36]:
pd.crosstab(train_df['Date'], train_df['Country/Region'])

Country/Region,Afghanistan,Albania,Algeria,Andorra,Antigua and Barbuda,Argentina,Armenia,Aruba,Australia,Austria,Azerbaijan,Bahrain,Bangladesh,Barbados,Belarus,Belgium,Benin,Bhutan,Bolivia,Bosnia and Herzegovina,Brazil,Brunei,Bulgaria,Burkina Faso,Cambodia,Cameroon,Canada,Central African Republic,Chile,China,Colombia,Congo (Brazzaville),Congo (Kinshasa),Costa Rica,Cote d'Ivoire,Croatia,Cruise Ship,Cuba,Cyprus,Czechia,Denmark,Djibouti,Dominican Republic,Ecuador,Egypt,Equatorial Guinea,Estonia,Eswatini,Ethiopia,Finland,...,Pakistan,Panama,Paraguay,Peru,Philippines,Poland,Portugal,Puerto Rico,Qatar,Republic of the Congo,Reunion,Romania,Russia,Rwanda,Saint Lucia,Saint Vincent and the Grenadines,San Marino,Saudi Arabia,Senegal,Serbia,Seychelles,Singapore,Slovakia,Slovenia,Somalia,South Africa,Spain,Sri Lanka,Sudan,Suriname,Sweden,Switzerland,Taiwan*,Tanzania,Thailand,The Bahamas,The Gambia,Togo,Trinidad and Tobago,Tunisia,Turkey,US,Ukraine,United Arab Emirates,United Kingdom,Uruguay,Uzbekistan,Venezuela,Vietnam,Zambia
Date,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
2020-01-22,1,1,1,1,1,1,1,1,9,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,11,1,1,33,1,1,1,1,1,1,1,1,1,1,2,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,58,1,1,5,1,1,1,1,1
2020-01-23,1,1,1,1,1,1,1,1,9,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,11,1,1,33,1,1,1,1,1,1,1,1,1,1,2,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,58,1,1,5,1,1,1,1,1
2020-01-24,1,1,1,1,1,1,1,1,9,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,11,1,1,33,1,1,1,1,1,1,1,1,1,1,2,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,58,1,1,5,1,1,1,1,1
2020-01-25,1,1,1,1,1,1,1,1,9,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,11,1,1,33,1,1,1,1,1,1,1,1,1,1,2,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,58,1,1,5,1,1,1,1,1
2020-01-26,1,1,1,1,1,1,1,1,9,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,11,1,1,33,1,1,1,1,1,1,1,1,1,1,2,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,58,1,1,5,1,1,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2020-03-20,1,1,1,1,1,1,1,1,9,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,11,1,1,33,1,1,1,1,1,1,1,1,1,1,2,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,58,1,1,5,1,1,1,1,1
2020-03-21,1,1,1,1,1,1,1,1,9,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,11,1,1,33,1,1,1,1,1,1,1,1,1,1,2,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,58,1,1,5,1,1,1,1,1
2020-03-22,1,1,1,1,1,1,1,1,9,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,11,1,1,33,1,1,1,1,1,1,1,1,1,1,2,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,58,1,1,5,1,1,1,1,1
2020-03-23,1,1,1,1,1,1,1,1,9,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,11,1,1,33,1,1,1,1,1,1,1,1,1,1,2,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,58,1,1,5,1,1,1,1,1
2020-03-24,1,1,1,1,1,1,1,1,9,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,11,1,1,33,1,1,1,1,1,1,1,1,1,1,2,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,58,1,1,5,1,1,1,1,1

In [37]:
train_df_schema = pd.io.json.build_table_schema(train_df)

In [38]:
train_df_schema

{'fields': [{'name': 'index', 'type': 'integer'},
  {'name': 'Id', 'type': 'integer'},
  {'name': 'Province/State', 'type': 'string'},
  {'name': 'Country/Region', 'type': 'string'},
  {'name': 'Lat', 'type': 'number'},
  {'name': 'Long', 'type': 'number'},
  {'name': 'Date', 'type': 'string'},
  {'name': 'ConfirmedCases', 'type': 'number'},
  {'name': 'Fatalities', 'type': 'number'}],
 'primaryKey': ['index'],
 'pandas_version': '0.20.0'}

In [39]:
train_df.head(3)

,Id,Province/State,Country/Region,Lat,Long,Date,ConfirmedCases,Fatalities
0,1,NaN,Afghanistan,33.0,65.0,2020-01-22,0.0,0.0
1,2,NaN,Afghanistan,33.0,65.0,2020-01-23,0.0,0.0
2,3,NaN,Afghanistan,33.0,65.0,2020-01-24,0.0,0.0

In [40]:
train_forecast_schema = []
for elem in train_df_schema['fields']:
    if elem['type'] in ('integer', 'string', 'float', 'double'):
        train_forecast_schema.append(
        {
            'AttributeName': re.sub('\W+','_', elem['name']),
            'AttributeType': elem['type']
        })
    elif elem['type'] =='number':
        train_forecast_schema.append(
        {
            'AttributeName': re.sub('\W+','_', elem['name']),
            'AttributeType': 'float'
        })

In [41]:
train_forecast_schema_final = {
    'Attributes': train_forecast_schema
}

In [42]:
print(json.dumps(train_forecast_schema_final))

{"Attributes": [{"AttributeName": "index", "AttributeType": "integer"}, {"AttributeName": "Id", "AttributeType": "integer"}, {"AttributeName": "Province_State", "AttributeType": "string"}, {"AttributeName": "Country_Region", "AttributeType": "string"}, {"AttributeName": "Lat", "AttributeType": "float"}, {"AttributeName": "Long", "AttributeType": "float"}, {"AttributeName": "Date", "AttributeType": "string"}, {"AttributeName": "ConfirmedCases", "AttributeType": "float"}, {"AttributeName": "Fatalities", "AttributeType": "float"}]}

In [43]:
train_final_schema = """
{
  "Attributes": [
    {
      "AttributeName": "id",
      "AttributeType": "string"
    },
    {
      "AttributeName": "Province_State",
      "AttributeType": "string"
    },
    {
      "AttributeName": "item_id",
      "AttributeType": "string"
    },
    {
      "AttributeName": "Lat",
      "AttributeType": "string"
    },
    {
      "AttributeName": "Lon",
      "AttributeType": "string"
    },
    {
      "AttributeName": "timestamp",
      "AttributeType": "timestamp"
    },
    {
      "AttributeName": "target_value",
      "AttributeType": "float"
    },
    {
      "AttributeName": "Fatalities",
      "AttributeType": "string"
    }
  ]
}
"""

In [177]:
kaggle_week_5_confirmedcases_schema = """
{
  "Attributes": [
    {
      "AttributeName": "id",
      "AttributeType": "string"
    },
    {
      "AttributeName": "County",
      "AttributeType": "string"
    },
    {
      "AttributeName": "Province_State",
      "AttributeType": "string"
    },
    {
      "AttributeName": "item_id",
      "AttributeType": "string"
    },
    {
      "AttributeName": "Population",
      "AttributeType": "string"
    },
    {
      "AttributeName": "Weight",
      "AttributeType": "string"
    },
    {
      "AttributeName": "timestamp",
      "AttributeType": "timestamp"
    },
    {
      "AttributeName": "ConfirmedCases",
      "AttributeType": "string"
    },
    {
      "AttributeName": "target_value",
      "AttributeType": "float"
    }
  ]
}
"""

In [172]:
dataset_group_name = "covid19_week5"
forecast_domain = "CUSTOM"

In [173]:
# Creating client to access forecast
forecast_client = boto3.client('forecast', region_name='eu-west-1')

In [174]:
# Creating dataset group
dataset_group_response = forecast_client.create_dataset_group(
    DatasetGroupName=dataset_group_name,
    Domain=forecast_domain
)

In [180]:
dataset_group_response

{'DatasetGroupArn': 'arn:aws:forecast:eu-west-1:700238584577:dataset-group/covid19_week5',
 'ResponseMetadata': {'RequestId': 'e280505b-f54a-4a21-b66c-b195608efef1',
  'HTTPStatusCode': 200,
  'HTTPHeaders': {'content-type': 'application/x-amz-json-1.1',
   'date': 'Wed, 20 May 2020 21:45:32 GMT',
   'x-amzn-requestid': 'e280505b-f54a-4a21-b66c-b195608efef1',
   'content-length': '89',
   'connection': 'keep-alive'},
  'RetryAttempts': 0}}

In [178]:
# Creating Target time series dataset
dataset_response = forecast_client.create_dataset(
    DatasetName='covid19_week5_confirmedcases_train',
    Domain='CUSTOM',
    DatasetType='TARGET_TIME_SERIES',
    DataFrequency='D',
    Schema={
  "Attributes": [
        {
          "AttributeName": "id",
          "AttributeType": "string"
        },
        {
          "AttributeName": "County",
          "AttributeType": "string"
        },
        {
          "AttributeName": "Province_State",
          "AttributeType": "string"
        },
        {
          "AttributeName": "item_id",
          "AttributeType": "string"
        },
        {
          "AttributeName": "Population",
          "AttributeType": "string"
        },
        {
          "AttributeName": "Weight",
          "AttributeType": "string"
        },
        {
          "AttributeName": "timestamp",
          "AttributeType": "timestamp"
        },
        {
          "AttributeName": "ConfirmedCases",
          "AttributeType": "string"
        },
        {
          "AttributeName": "target_value",
          "AttributeType": "float"
        }
      ]
    }
)

In [181]:
dataset_response

{'DatasetArn': 'arn:aws:forecast:eu-west-1:700238584577:dataset/covid19_week5_confirmedcases_train',
 'ResponseMetadata': {'RequestId': '53a4e113-7dae-42e5-9c40-7f30fa7804c5',
  'HTTPStatusCode': 200,
  'HTTPHeaders': {'content-type': 'application/x-amz-json-1.1',
   'date': 'Wed, 20 May 2020 21:51:00 GMT',
   'x-amzn-requestid': '53a4e113-7dae-42e5-9c40-7f30fa7804c5',
   'content-length': '99',
   'connection': 'keep-alive'},
  'RetryAttempts': 0}}

In [187]:
# Describe dataset
forecast_client.describe_dataset(
    DatasetArn=dataset_response['DatasetArn']
)

{'DatasetArn': 'arn:aws:forecast:eu-west-1:700238584577:dataset/covid19_week5_confirmedcases_train',
 'DatasetName': 'covid19_week5_confirmedcases_train',
 'Domain': 'CUSTOM',
 'DatasetType': 'TARGET_TIME_SERIES',
 'DataFrequency': 'D',
 'Schema': {'Attributes': [{'AttributeName': 'id', 'AttributeType': 'string'},
   {'AttributeName': 'County', 'AttributeType': 'string'},
   {'AttributeName': 'Province_State', 'AttributeType': 'string'},
   {'AttributeName': 'item_id', 'AttributeType': 'string'},
   {'AttributeName': 'Population', 'AttributeType': 'string'},
   {'AttributeName': 'Weight', 'AttributeType': 'string'},
   {'AttributeName': 'timestamp', 'AttributeType': 'timestamp'},
   {'AttributeName': 'ConfirmedCases', 'AttributeType': 'string'},
   {'AttributeName': 'target_value', 'AttributeType': 'float'}]},
 'EncryptionConfig': {},
 'Status': 'ACTIVE',
 'CreationTime': datetime.datetime(2020, 5, 20, 22, 51, 0, 327000, tzinfo=tzlocal()),
 'LastModificationTime': datetime.datetime(2020, 5, 20, 23, 9, 4, 845000, tzinfo=tzlocal()),
 'ResponseMetadata': {'RequestId': '329e29e7-44c8-4c09-91ed-d8d52cb45712',
  'HTTPStatusCode': 200,
  'HTTPHeaders': {'content-type': 'application/x-amz-json-1.1',
   'date': 'Wed, 20 May 2020 22:29:03 GMT',
   'x-amzn-requestid': '329e29e7-44c8-4c09-91ed-d8d52cb45712',
   'content-length': '857',
   'connection': 'keep-alive'},
  'RetryAttempts': 0}}

In [ ]:
role_policy = """
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Action": [
                "s3:ListBucket"
            ],
            "Effect": "Allow",
            "Resource": [
                "arn:aws:s3:::exploring-ml-tools-eu-west-1"
            ]
        },
        {
            "Action": [
                "s3:GetObject",
                "s3:PutObject",
                "s3:DeleteObject"
            ],
            "Effect": "Allow",
            "Resource": [
                "arn:aws:s3:::exploring-ml-tools-eu-west-1/*"
            ]
        }
    ]
}
"""

In [183]:
# Creating dataset import job
import_job_response = forecast_client.create_dataset_import_job(
    DatasetImportJobName='week5_confirmed_cases_import',
    DatasetArn=dataset_response['DatasetArn'],
    DataSource={
        'S3Config': {
            'Path': 's3://exploring-ml-tools-eu-west-1/amazon-forecast/assets/covid_19_week_5/target_time_series/confirmedcases/',
            'RoleArn': 'arn:aws:iam::700238584577:role/service-role/AmazonForecast-ExecutionRole-1589874597925'
        }
    },
    TimestampFormat='yyyy-MM-dd'
)

In [186]:
import_job_response

{'DatasetImportJobArn': 'arn:aws:forecast:eu-west-1:700238584577:dataset-import-job/covid19_week5_confirmedcases_train/week5_confirmed_cases_import',
 'ResponseMetadata': {'RequestId': '910ff6d2-0e8f-48f2-ba52-8e56b371010b',
  'HTTPStatusCode': 200,
  'HTTPHeaders': {'content-type': 'application/x-amz-json-1.1',
   'date': 'Wed, 20 May 2020 22:03:57 GMT',
   'x-amzn-requestid': '910ff6d2-0e8f-48f2-ba52-8e56b371010b',
   'content-length': '148',
   'connection': 'keep-alive'},
  'RetryAttempts': 0}}

In [189]:
# Update dataset group with dataset
update_ds_group_response = forecast_client.update_dataset_group(
    DatasetGroupArn=dataset_group_response['DatasetGroupArn'],
    DatasetArns=[
        dataset_response['DatasetArn']
    ]
)

In [190]:
update_ds_group_response

{'ResponseMetadata': {'RequestId': '6a486161-d8ac-4917-aced-94a3acf43e90',
  'HTTPStatusCode': 200,
  'HTTPHeaders': {'content-type': 'application/x-amz-json-1.1',
   'date': 'Wed, 20 May 2020 22:30:01 GMT',
   'x-amzn-requestid': '6a486161-d8ac-4917-aced-94a3acf43e90',
   'content-length': '2',
   'connection': 'keep-alive'},
  'RetryAttempts': 0}}

In [191]:
# Create predictor using automl

predictor_response = forecast_client.create_predictor(
    PredictorName='covid19_confirmed_case_automl',
    ForecastHorizon=14,
    PerformAutoML=True,
    PerformHPO=False,
    InputDataConfig={
        'DatasetGroupArn': dataset_group_response['DatasetGroupArn']
    },
    FeaturizationConfig={
        'ForecastFrequency': 'D'
    }
)

In [192]:
predictor_response

{'PredictorArn': 'arn:aws:forecast:eu-west-1:700238584577:predictor/covid19_confirmed_case_automl',
 'ResponseMetadata': {'RequestId': 'bf49711a-b8a3-4a1c-912a-97bb625679fd',
  'HTTPStatusCode': 200,
  'HTTPHeaders': {'content-type': 'application/x-amz-json-1.1',
   'date': 'Wed, 20 May 2020 22:31:52 GMT',
   'x-amzn-requestid': 'bf49711a-b8a3-4a1c-912a-97bb625679fd',
   'content-length': '98',
   'connection': 'keep-alive'},
  'RetryAttempts': 0}}

In [200]:
forecast_client.list_predictors(
    Filters=[
        {
            'Key': 'DatasetGroupArn',
            'Value': dataset_group_response['DatasetGroupArn'],
            'Condition': 'IS'
        }
    ]
)

{'Predictors': [{'PredictorArn': 'arn:aws:forecast:eu-west-1:700238584577:predictor/covid19_confirmed_case_automl',
   'PredictorName': 'covid19_confirmed_case_automl',
   'DatasetGroupArn': 'arn:aws:forecast:eu-west-1:700238584577:dataset-group/covid19_week5',
   'Status': 'ACTIVE',
   'CreationTime': datetime.datetime(2020, 5, 20, 23, 31, 52, 981000, tzinfo=tzlocal()),
   'LastModificationTime': datetime.datetime(2020, 5, 21, 0, 26, 32, 913000, tzinfo=tzlocal())}],
 'ResponseMetadata': {'RequestId': '7ca12399-bed8-4e0e-bb40-5cb1a741d22f',
  'HTTPStatusCode': 200,
  'HTTPHeaders': {'content-type': 'application/x-amz-json-1.1',
   'date': 'Wed, 20 May 2020 23:38:24 GMT',
   'x-amzn-requestid': '7ca12399-bed8-4e0e-bb40-5cb1a741d22f',
   'content-length': '341',
   'connection': 'keep-alive'},
  'RetryAttempts': 0}}

In [201]:
# Get accuracy metric 
forecast_client.get_accuracy_metrics(
    PredictorArn=predictor_response['PredictorArn']
)

{'PredictorEvaluationResults': [{'AlgorithmArn': 'arn:aws:forecast:::algorithm/ARIMA',
   'TestWindows': [{'EvaluationType': 'SUMMARY',
     'Metrics': {'RMSE': 1236.6531071479014,
      'WeightedQuantileLosses': [{'Quantile': 0.9,
        'LossValue': 0.18955675698559962},
       {'Quantile': 0.5, 'LossValue': 0.2752075136407778},
       {'Quantile': 0.1, 'LossValue': 0.13672475334418394}]}},
    {'TestWindowStart': datetime.datetime(2020, 5, 5, 1, 0, tzinfo=tzlocal()),
     'TestWindowEnd': datetime.datetime(2020, 5, 19, 1, 0, tzinfo=tzlocal()),
     'ItemCount': 187,
     'EvaluationType': 'COMPUTED',
     'Metrics': {'RMSE': 1236.653107147902,
      'WeightedQuantileLosses': [{'Quantile': 0.9,
        'LossValue': 0.1895567569855996},
       {'Quantile': 0.5, 'LossValue': 0.27520751364077767},
       {'Quantile': 0.1, 'LossValue': 0.13672475334418388}]}}]},
  {'AlgorithmArn': 'arn:aws:forecast:::algorithm/Deep_AR_Plus',
   'TestWindows': [{'EvaluationType': 'SUMMARY',
     'Metrics': {'RMSE': 1058.5317072269838,
      'WeightedQuantileLosses': [{'Quantile': 0.9,
        'LossValue': 0.17381843236561664},
       {'Quantile': 0.5, 'LossValue': 0.3020061180969752},
       {'Quantile': 0.1, 'LossValue': 0.13936768088716472}]}},
    {'TestWindowStart': datetime.datetime(2020, 5, 5, 1, 0, tzinfo=tzlocal()),
     'TestWindowEnd': datetime.datetime(2020, 5, 19, 1, 0, tzinfo=tzlocal()),
     'ItemCount': 187,
     'EvaluationType': 'COMPUTED',
     'Metrics': {'RMSE': 1058.5317072269838,
      'WeightedQuantileLosses': [{'Quantile': 0.9,
        'LossValue': 0.17381843236561656},
       {'Quantile': 0.5, 'LossValue': 0.30200611809697514},
       {'Quantile': 0.1, 'LossValue': 0.13936768088716475}]}}]},
  {'AlgorithmArn': 'arn:aws:forecast:::algorithm/ETS',
   'TestWindows': [{'EvaluationType': 'SUMMARY',
     'Metrics': {'RMSE': 1717.6674815634772,
      'WeightedQuantileLosses': [{'Quantile': 0.9,
        'LossValue': 0.20097806052211598},
       {'Quantile': 0.5, 'LossValue': 0.34772992287824156},
       {'Quantile': 0.1, 'LossValue': 0.20037132846922612}]}},
    {'TestWindowStart': datetime.datetime(2020, 5, 5, 1, 0, tzinfo=tzlocal()),
     'TestWindowEnd': datetime.datetime(2020, 5, 19, 1, 0, tzinfo=tzlocal()),
     'ItemCount': 187,
     'EvaluationType': 'COMPUTED',
     'Metrics': {'RMSE': 1717.6674815634776,
      'WeightedQuantileLosses': [{'Quantile': 0.9,
        'LossValue': 0.20097806052211603},
       {'Quantile': 0.5, 'LossValue': 0.3477299228782414},
       {'Quantile': 0.1, 'LossValue': 0.20037132846922615}]}}]},
  {'AlgorithmArn': 'arn:aws:forecast:::algorithm/Prophet',
   'TestWindows': [{'EvaluationType': 'SUMMARY',
     'Metrics': {'RMSE': 3231.8303961612137,
      'WeightedQuantileLosses': [{'Quantile': 0.9,
        'LossValue': 0.2943967876573458},
       {'Quantile': 0.5, 'LossValue': 0.6344526339131902},
       {'Quantile': 0.1, 'LossValue': 0.45300412522500094}]}},
    {'TestWindowStart': datetime.datetime(2020, 5, 5, 1, 0, tzinfo=tzlocal()),
     'TestWindowEnd': datetime.datetime(2020, 5, 19, 1, 0, tzinfo=tzlocal()),
     'ItemCount': 187,
     'EvaluationType': 'COMPUTED',
     'Metrics': {'RMSE': 3231.830396161214,
      'WeightedQuantileLosses': [{'Quantile': 0.9,
        'LossValue': 0.2943967876573457},
       {'Quantile': 0.5, 'LossValue': 0.6344526339131898},
       {'Quantile': 0.1, 'LossValue': 0.45300412522500083}]}}]},
  {'AlgorithmArn': 'arn:aws:forecast:::algorithm/NPTS',
   'TestWindows': [{'EvaluationType': 'SUMMARY',
     'Metrics': {'RMSE': 4832.3551909361395,
      'WeightedQuantileLosses': [{'Quantile': 0.9,
        'LossValue': 0.43352091983526725},
       {'Quantile': 0.5, 'LossValue': 0.9204653636933573},
       {'Quantile': 0.1, 'LossValue': 0.20319956009346957}]}},
    {'TestWindowStart': datetime.datetime(2020, 5, 5, 1, 0, tzinfo=tzlocal()),
     'TestWindowEnd': datetime.datetime(2020, 5, 19, 1, 0, tzinfo=tzlocal()),
     'ItemCount': 187,
     'EvaluationType': 'COMPUTED',
     'Metrics': {'RMSE': 4832.3551909361395,
      'WeightedQuantileLosses': [{'Quantile': 0.9,
        'LossValue': 0.43352091983526725},
       {'Quantile': 0.5, 'LossValue': 0.9204653636933573},
       {'Quantile': 0.1, 'LossValue': 0.20319956009346957}]}}]}],
 'ResponseMetadata': {'RequestId': 'e3a3e73c-8be9-465b-ab3a-c1ac3819f2b3',
  'HTTPStatusCode': 200,
  'HTTPHeaders': {'content-type': 'application/x-amz-json-1.1',
   'date': 'Wed, 20 May 2020 23:38:27 GMT',
   'x-amzn-requestid': 'e3a3e73c-8be9-465b-ab3a-c1ac3819f2b3',
   'content-length': '3161',
   'connection': 'keep-alive'},
  'RetryAttempts': 0}}

In [202]:
# Create forecast
forecast_response = forecast_client.create_forecast(
    ForecastName='covid19_automl_forecast',
    PredictorArn=predictor_response['PredictorArn'],
    ForecastTypes=[
        "0.1", "0.5", "0.9", "0.95", "0.99"
    ]
)

In [203]:
forecast_response

{'ForecastArn': 'arn:aws:forecast:eu-west-1:700238584577:forecast/covid19_automl_forecast',
 'ResponseMetadata': {'RequestId': '3876e66a-cd39-4952-bfff-a3d0d7a27f39',
  'HTTPStatusCode': 200,
  'HTTPHeaders': {'content-type': 'application/x-amz-json-1.1',
   'date': 'Wed, 20 May 2020 23:38:31 GMT',
   'x-amzn-requestid': '3876e66a-cd39-4952-bfff-a3d0d7a27f39',
   'content-length': '90',
   'connection': 'keep-alive'},
  'RetryAttempts': 0}}

In [208]:
# Describe Forecast
forecast_client.describe_forecast(
    ForecastArn=forecast_response['ForecastArn']
)

{'ForecastArn': 'arn:aws:forecast:eu-west-1:700238584577:forecast/covid19_automl_forecast',
 'ForecastName': 'covid19_automl_forecast',
 'ForecastTypes': ['0.1', '0.5', '0.9', '0.95', '0.99'],
 'PredictorArn': 'arn:aws:forecast:eu-west-1:700238584577:predictor/covid19_confirmed_case_automl',
 'DatasetGroupArn': 'arn:aws:forecast:eu-west-1:700238584577:dataset-group/covid19_week5',
 'Status': 'ACTIVE',
 'CreationTime': datetime.datetime(2020, 5, 21, 0, 38, 31, 739000, tzinfo=tzlocal()),
 'LastModificationTime': datetime.datetime(2020, 5, 21, 0, 59, 38, 539000, tzinfo=tzlocal()),
 'ResponseMetadata': {'RequestId': 'ae4d074d-19a7-475c-9738-5dc9cec3b69b',
  'HTTPStatusCode': 200,
  'HTTPHeaders': {'content-type': 'application/x-amz-json-1.1',
   'date': 'Thu, 21 May 2020 00:32:43 GMT',
   'x-amzn-requestid': 'ae4d074d-19a7-475c-9738-5dc9cec3b69b',
   'content-length': '456',
   'connection': 'keep-alive'},
  'RetryAttempts': 0}}

In [88]:
forecast_client.list_forecasts(
    Filters=[
        {
            'Key': 'PredictorArn',
            'Value': predictor_response['PredictorArn'],
            'Condition': 'IS'
        },
    ]
)

{'Forecasts': [{'ForecastArn': 'arn:aws:forecast:eu-west-1:700238584577:forecast/covid19_automl_forecast',
   'ForecastName': 'covid19_automl_forecast',
   'PredictorArn': 'arn:aws:forecast:eu-west-1:700238584577:predictor/covid19_confirmed_case_automl',
   'DatasetGroupArn': 'arn:aws:forecast:eu-west-1:700238584577:dataset-group/covid19',
   'Status': 'ACTIVE',
   'CreationTime': datetime.datetime(2020, 5, 20, 9, 39, 4, 399000, tzinfo=tzlocal()),
   'LastModificationTime': datetime.datetime(2020, 5, 20, 9, 58, 49, 967000, tzinfo=tzlocal())}],
 'ResponseMetadata': {'RequestId': 'ad15029d-40a5-429a-a74a-d2ad8c07a137',
  'HTTPStatusCode': 200,
  'HTTPHeaders': {'content-type': 'application/x-amz-json-1.1',
   'date': 'Wed, 20 May 2020 09:02:32 GMT',
   'x-amzn-requestid': 'ad15029d-40a5-429a-a74a-d2ad8c07a137',
   'content-length': '416',
   'connection': 'keep-alive'},
  'RetryAttempts': 0}}

In [209]:
# Create forecast export job
export_forecast_response = forecast_client.create_forecast_export_job(
    ForecastExportJobName='Week6Foecast',
    ForecastArn=forecast_response['ForecastArn'],
    Destination={
        'S3Config': {
            'Path': 's3://exploring-ml-tools-eu-west-1/amazon-forecast/assets/covid_19_week_5/week6_predicted',
            'RoleArn': 'arn:aws:iam::700238584577:role/service-role/AmazonForecast-ExecutionRole-1589874597925'
        }
    }
)

In [95]:
export_forecast_response

{'ForecastExportJobArn': 'arn:aws:forecast:eu-west-1:700238584577:forecast-export-job/covid19_automl_forecast/Week2Foecast',
 'ResponseMetadata': {'RequestId': 'b0198263-9ae3-41c1-b3ae-a5188c9d1687',
  'HTTPStatusCode': 200,
  'HTTPHeaders': {'content-type': 'application/x-amz-json-1.1',
   'date': 'Wed, 20 May 2020 09:15:33 GMT',
   'x-amzn-requestid': 'b0198263-9ae3-41c1-b3ae-a5188c9d1687',
   'content-length': '123',
   'connection': 'keep-alive'},
  'RetryAttempts': 0}}

## Clean up

In [140]:
# Delete forecast
forecast_client.delete_forecast(
    ForecastArn=forecast_response['ForecastArn']
)

{'ResponseMetadata': {'RequestId': 'fcf178b7-c50a-41cf-a62b-34883e973dca',
  'HTTPStatusCode': 200,
  'HTTPHeaders': {'content-type': 'application/x-amz-json-1.1',
   'date': 'Wed, 20 May 2020 10:56:53 GMT',
   'x-amzn-requestid': 'fcf178b7-c50a-41cf-a62b-34883e973dca',
   'content-length': '0',
   'connection': 'keep-alive'},
  'RetryAttempts': 0}}

In [142]:
# Delete predictor
forecast_client.delete_predictor(
    PredictorArn=predictor_response['PredictorArn']
)

{'ResponseMetadata': {'RequestId': 'b9a80ab6-8b74-4077-aac9-1bfe64b38350',
  'HTTPStatusCode': 200,
  'HTTPHeaders': {'content-type': 'application/x-amz-json-1.1',
   'date': 'Wed, 20 May 2020 10:57:26 GMT',
   'x-amzn-requestid': 'b9a80ab6-8b74-4077-aac9-1bfe64b38350',
   'content-length': '0',
   'connection': 'keep-alive'},
  'RetryAttempts': 0}}

In [149]:
# Delete dataset import job
forecast_client.delete_dataset_import_job(
    DatasetImportJobArn=import_job_response['DatasetImportJobArn']
)

{'ResponseMetadata': {'RequestId': 'dc1cd809-fa3e-4ed5-b5cc-9467f65d1170',
  'HTTPStatusCode': 200,
  'HTTPHeaders': {'content-type': 'application/x-amz-json-1.1',
   'date': 'Wed, 20 May 2020 11:02:46 GMT',
   'x-amzn-requestid': 'dc1cd809-fa3e-4ed5-b5cc-9467f65d1170',
   'content-length': '0',
   'connection': 'keep-alive'},
  'RetryAttempts': 0}}

In [151]:
# Delete Dataset
forecast_client.delete_dataset(
    DatasetArn=dataset_response['DatasetArn']
)

{'ResponseMetadata': {'RequestId': 'c2e60df2-0499-4938-82c1-37fe7f561db9',
  'HTTPStatusCode': 200,
  'HTTPHeaders': {'content-type': 'application/x-amz-json-1.1',
   'date': 'Wed, 20 May 2020 11:03:14 GMT',
   'x-amzn-requestid': 'c2e60df2-0499-4938-82c1-37fe7f561db9',
   'content-length': '0',
   'connection': 'keep-alive'},
  'RetryAttempts': 0}}

In [145]:
# Delete Dataset Group
# we can delete dataset group without deleting dataset
forecast_client.delete_dataset_group(
    DatasetGroupArn=dataset_group_response['DatasetGroupArn']
)

{'ResponseMetadata': {'RequestId': 'bb129022-743c-4c06-bc00-22f4817b9118',
  'HTTPStatusCode': 200,
  'HTTPHeaders': {'content-type': 'application/x-amz-json-1.1',
   'date': 'Wed, 20 May 2020 10:58:38 GMT',
   'x-amzn-requestid': 'bb129022-743c-4c06-bc00-22f4817b9118',
   'content-length': '0',
   'connection': 'keep-alive'},
  'RetryAttempts': 0}}